### ISSUE TITLE
Discovery pane -template has changed

### ISSUE THREAD

**Issue by msaguin** [tableau/discover-pane-template#1]
Dear discovery pane owner,

I've try couple of weeks ago to customize the discovery pane and it was all good. But it seems that something has changed since that so I'm wondering if the template is still up to date. 
Eg. If I copy paste the template and preview the html page, I get this result : 
![image](https://user-images.githubusercontent.com/34234434/99658312-9a110b00-2a5f-11eb-95d2-3340418b36f2.png)

Let me know if it's me doing crap of if the template has changed :).

Thank you,

Best regards, 

Mathilde

**Comment by msaguin** [comment]
I cannot access to the css href. Could it have a correlation between the two ?

**Comment by ARob0531** [comment]
I am having the same issue.  How was this resolved?  Really wanting this to work.

**Comment by msaguin** [comment]
Hi Rob,

We've started do a similar thing as discovery pane but it's less appealing.
I hope it helps!

Mathilde

`<!DOCTYPE html>

<html lang="en-us">
<head>
	<meta charset="UTF-8">
    <title>Discover Pane - Desktop | Tableau Software</title>
    <style type="text/css">
    body 
    {	background-color: #EBEBEB	;
		color : #585858;
		font-family: verdana;
		font-size:12px
    } 
    img 
    { 
      max-width: 100%; 
      height: auto; 
    } 

    .discover-title
    {color: #00a9e0;
      text-align: left;
      margin-left: 0px;
      margin-top: 50px;
      margin-bottom: 50px;
      font-size: 200%;
	  font-family: cursive;
    }
	
	h2{color: #00a9e0	;
		margin-left: 0px;
	}
	
	div{  background-color: #DADADA;
	  padding: 0px;
		color : #A8A8A8;
	  display: none;
	  
	}
	
	a:link {
	  color: #696969;
	  text-decoration: none;
	}
	a:visited {
	  color: #696969;
	  text-decoration: none;
	}
	a:hover {
	  text-decoration: none;         
	}
	a:active {
	  color: #696969;
	  text-decoration: none;
	}

    section
    {
        display: block;
    }
	

	li{list-style-type:none;
		margin-left: 0px;
		line-height: 1.7;
	}
	li:hover{background-color: #DADADA;
	}
	span:hover + div {
		display: block;}
	
    </style>
</head>
<body >
        
		
		 <section> 
          <h2>Tableau Server</h2>
          <ul>
            <li class="blog"><a href="https:***">Tableau Server</a></li>
			 <br> <br> 
          </ul>
        </section>
		
        <section >
          <h2>Training </h2>
          <ul>
            <li class="alpha">
              <span><a href="https://www.tableau.com/learn/tutorials/on-demand/getting-started?reg-delay=true">
                Getting Started</a></span>
                <div>Connecting to your data for the first time? This is the video for you.</div>
              
            </li>
            <li class="alpha">
              <span><a href="https://www.tableau.com/learn/tutorials/on-demand/getting-started-data?reg-delay=true">
                Connecting to Data</a></span>
                <div>Get your data into Tableau; connect to files, single or multiple tables.</div>
              
            </li>
            <li class="alpha">
              <span><a href="https:***" >
                InternalTraining Recordings</a></span>
                <div>Learn by watching our internal training to Tableau. Pick the topic you're interested in.</div>
              
            </li>

			
			<li class="alpha">
              <span><a href="https://public.tableau.com/en-us/gallery/?tab=viz-of-the-day&type=viz-of-the-day">
                Tableau Viz of the Day </a></span>
            </li>
			<br><br>
          </ul>
        </section>

        <section >
          <h2>Resources</h2>
          <ul class="personalize">


            <li class="blog">
			<span><a href="https:***">Blog  </a></span>
			<div>Our Visualization community</div></li>

			<li class="alpha">
              <span><a href="https:***">
                Request Tableau License</a></span>
              <div>Please fill the form to request your tableau license</div>
            </li>
            

			<li class="alpha">
              <span><a href="https:***">
                Our Logi Tableau Events</a></span>
              <div>Add our Tableau Learning opportunities to your calendar</div>

			  
            <li>  <a href="https:***">
                Workbook Description
              </a></li>
			  
			  
			<li class="alpha">
              <span><a href="https:***" >
                Request Tableau License</a> </span>
              <div>Please fill the form to request your tableau license</div>
              
            </li>
          </ul>
        </section>


</body>
</html>`

**Comment by ARob0531** [comment]
Is Tableau responding to this?

**Comment by acknapp** [comment]
Hi @msaguin and  @ARob0531  -
This should be resolved now with commit 0eb57ff.  Let me know should you continue to have issues.

**Comment by sprati0510** [comment]
Closing since no response. Please reopen if issue reoccurs.
